/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * Messaging app API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Register a new account
 */
export declare const registerBodyUsernameMin = 3;
export declare const registerBodyUsernameMax = 30;
export declare const registerBodyDisplayNameMax = 50;
export declare const registerBodyPasswordMin = 6;
export declare const RegisterBody: zod.ZodObject<{
    username: zod.ZodString;
    displayName: zod.ZodString;
    password: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    password: string;
}, {
    username: string;
    displayName: string;
    password: string;
}>;
export declare const RegisterResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isOnline: zod.ZodBoolean;
    lastSeen: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}>;
/**
 * @summary Log in
 */
export declare const LoginBody: zod.ZodObject<{
    username: zod.ZodString;
    password: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    password: string;
}, {
    username: string;
    password: string;
}>;
export declare const LoginResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isOnline: zod.ZodBoolean;
    lastSeen: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}>;
/**
 * @summary Log out
 */
export declare const LogoutResponse: zod.ZodObject<{
    ok: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    ok: boolean;
}, {
    ok: boolean;
}>;
/**
 * @summary Get current user
 */
export declare const GetMeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isOnline: zod.ZodBoolean;
    lastSeen: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}>;
/**
 * @summary List or search users
 */
export declare const ListUsersQueryParams: zod.ZodObject<{
    search: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    search?: string | undefined;
}, {
    search?: string | undefined;
}>;
export declare const ListUsersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isOnline: zod.ZodBoolean;
    lastSeen: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}>;
export declare const ListUsersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isOnline: zod.ZodBoolean;
    lastSeen: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}>, "many">;
/**
 * @summary Update current user profile
 */
export declare const updateMeBodyDisplayNameMax = 50;
export declare const updateMeBodyBioMax = 200;
export declare const UpdateMeBody: zod.ZodObject<{
    displayName: zod.ZodOptional<zod.ZodString>;
    bio: zod.ZodOptional<zod.ZodString>;
    avatarUrl: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    displayName?: string | undefined;
    avatarUrl?: string | undefined;
    bio?: string | undefined;
}, {
    displayName?: string | undefined;
    avatarUrl?: string | undefined;
    bio?: string | undefined;
}>;
export declare const UpdateMeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isOnline: zod.ZodBoolean;
    lastSeen: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}>;
/**
 * @summary Mark current user as online
 */
export declare const HeartbeatResponse: zod.ZodObject<{
    ok: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    ok: boolean;
}, {
    ok: boolean;
}>;
/**
 * @summary Get a user by ID
 */
export declare const GetUserParams: zod.ZodObject<{
    userId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    userId: number;
}, {
    userId: number;
}>;
export declare const GetUserResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    isOnline: zod.ZodBoolean;
    lastSeen: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}, {
    username: string;
    displayName: string;
    id: number;
    isOnline: boolean;
    lastSeen: Date;
    createdAt: Date;
    avatarUrl?: string | null | undefined;
    bio?: string | null | undefined;
}>;
/**
 * @summary List conversations for the current user
 */
export declare const ListConversationsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    participants: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, "many">;
    lastMessage: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        conversationId: zod.ZodNumber;
        senderId: zod.ZodNumber;
        sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
            id: zod.ZodNumber;
            username: zod.ZodString;
            displayName: zod.ZodString;
            avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            isOnline: zod.ZodBoolean;
            lastSeen: zod.ZodDate;
            createdAt: zod.ZodDate;
        }, "strip", zod.ZodTypeAny, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }>, zod.ZodNull]>>;
        content: zod.ZodString;
        editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
        createdAt: zod.ZodDate;
        reactions: zod.ZodArray<zod.ZodObject<{
            emoji: zod.ZodString;
            count: zod.ZodNumber;
            userIds: zod.ZodArray<zod.ZodNumber, "many">;
        }, "strip", zod.ZodTypeAny, {
            emoji: string;
            count: number;
            userIds: number[];
        }, {
            emoji: string;
            count: number;
            userIds: number[];
        }>, "many">;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }>, zod.ZodNull]>>;
    unreadCount: zod.ZodNumber;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}>;
export declare const ListConversationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    participants: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, "many">;
    lastMessage: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        conversationId: zod.ZodNumber;
        senderId: zod.ZodNumber;
        sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
            id: zod.ZodNumber;
            username: zod.ZodString;
            displayName: zod.ZodString;
            avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            isOnline: zod.ZodBoolean;
            lastSeen: zod.ZodDate;
            createdAt: zod.ZodDate;
        }, "strip", zod.ZodTypeAny, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }>, zod.ZodNull]>>;
        content: zod.ZodString;
        editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
        createdAt: zod.ZodDate;
        reactions: zod.ZodArray<zod.ZodObject<{
            emoji: zod.ZodString;
            count: zod.ZodNumber;
            userIds: zod.ZodArray<zod.ZodNumber, "many">;
        }, "strip", zod.ZodTypeAny, {
            emoji: string;
            count: number;
            userIds: number[];
        }, {
            emoji: string;
            count: number;
            userIds: number[];
        }>, "many">;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }>, zod.ZodNull]>>;
    unreadCount: zod.ZodNumber;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}>, "many">;
/**
 * @summary Create or get a conversation with another user
 */
export declare const CreateConversationBody: zod.ZodObject<{
    participantId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    participantId: number;
}, {
    participantId: number;
}>;
export declare const CreateConversationResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    participants: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, "many">;
    lastMessage: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        conversationId: zod.ZodNumber;
        senderId: zod.ZodNumber;
        sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
            id: zod.ZodNumber;
            username: zod.ZodString;
            displayName: zod.ZodString;
            avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            isOnline: zod.ZodBoolean;
            lastSeen: zod.ZodDate;
            createdAt: zod.ZodDate;
        }, "strip", zod.ZodTypeAny, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }>, zod.ZodNull]>>;
        content: zod.ZodString;
        editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
        createdAt: zod.ZodDate;
        reactions: zod.ZodArray<zod.ZodObject<{
            emoji: zod.ZodString;
            count: zod.ZodNumber;
            userIds: zod.ZodArray<zod.ZodNumber, "many">;
        }, "strip", zod.ZodTypeAny, {
            emoji: string;
            count: number;
            userIds: number[];
        }, {
            emoji: string;
            count: number;
            userIds: number[];
        }>, "many">;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }>, zod.ZodNull]>>;
    unreadCount: zod.ZodNumber;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}>;
/**
 * @summary Get a single conversation
 */
export declare const GetConversationParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
}, {
    conversationId: number;
}>;
export declare const GetConversationResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    participants: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, "many">;
    lastMessage: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        conversationId: zod.ZodNumber;
        senderId: zod.ZodNumber;
        sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
            id: zod.ZodNumber;
            username: zod.ZodString;
            displayName: zod.ZodString;
            avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            isOnline: zod.ZodBoolean;
            lastSeen: zod.ZodDate;
            createdAt: zod.ZodDate;
        }, "strip", zod.ZodTypeAny, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }>, zod.ZodNull]>>;
        content: zod.ZodString;
        editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
        createdAt: zod.ZodDate;
        reactions: zod.ZodArray<zod.ZodObject<{
            emoji: zod.ZodString;
            count: zod.ZodNumber;
            userIds: zod.ZodArray<zod.ZodNumber, "many">;
        }, "strip", zod.ZodTypeAny, {
            emoji: string;
            count: number;
            userIds: number[];
        }, {
            emoji: string;
            count: number;
            userIds: number[];
        }>, "many">;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }>, zod.ZodNull]>>;
    unreadCount: zod.ZodNumber;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}, {
    id: number;
    createdAt: Date;
    participants: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }[];
    unreadCount: number;
    updatedAt: Date;
    lastMessage?: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    } | null | undefined;
}>;
/**
 * @summary Mark all messages in a conversation as read
 */
export declare const MarkReadParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
}, {
    conversationId: number;
}>;
export declare const MarkReadResponse: zod.ZodObject<{
    ok: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    ok: boolean;
}, {
    ok: boolean;
}>;
/**
 * @summary Set typing indicator
 */
export declare const SetTypingParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
}, {
    conversationId: number;
}>;
export declare const SetTypingBody: zod.ZodObject<{
    isTyping: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    isTyping: boolean;
}, {
    isTyping: boolean;
}>;
export declare const SetTypingResponse: zod.ZodObject<{
    ok: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    ok: boolean;
}, {
    ok: boolean;
}>;
/**
 * @summary Get who is currently typing in a conversation
 */
export declare const GetTypingStatusParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
}, {
    conversationId: number;
}>;
export declare const GetTypingStatusResponseItem: zod.ZodObject<{
    userId: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    userId: number;
}, {
    username: string;
    displayName: string;
    userId: number;
}>;
export declare const GetTypingStatusResponse: zod.ZodArray<zod.ZodObject<{
    userId: zod.ZodNumber;
    username: zod.ZodString;
    displayName: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    displayName: string;
    userId: number;
}, {
    username: string;
    displayName: string;
    userId: number;
}>, "many">;
/**
 * @summary List messages in a conversation
 */
export declare const GetMessagesParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
}, {
    conversationId: number;
}>;
export declare const GetMessagesQueryParams: zod.ZodObject<{
    before: zod.ZodOptional<zod.ZodNumber>;
    limit: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    before?: number | undefined;
    limit?: number | undefined;
}, {
    before?: number | undefined;
    limit?: number | undefined;
}>;
export declare const GetMessagesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    senderId: zod.ZodNumber;
    sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, zod.ZodNull]>>;
    content: zod.ZodString;
    editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    reactions: zod.ZodArray<zod.ZodObject<{
        emoji: zod.ZodString;
        count: zod.ZodNumber;
        userIds: zod.ZodArray<zod.ZodNumber, "many">;
    }, "strip", zod.ZodTypeAny, {
        emoji: string;
        count: number;
        userIds: number[];
    }, {
        emoji: string;
        count: number;
        userIds: number[];
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}>;
export declare const GetMessagesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    senderId: zod.ZodNumber;
    sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, zod.ZodNull]>>;
    content: zod.ZodString;
    editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    reactions: zod.ZodArray<zod.ZodObject<{
        emoji: zod.ZodString;
        count: zod.ZodNumber;
        userIds: zod.ZodArray<zod.ZodNumber, "many">;
    }, "strip", zod.ZodTypeAny, {
        emoji: string;
        count: number;
        userIds: number[];
    }, {
        emoji: string;
        count: number;
        userIds: number[];
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}>, "many">;
/**
 * @summary Send a message
 */
export declare const SendMessageParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
}, {
    conversationId: number;
}>;
export declare const SendMessageBody: zod.ZodObject<{
    content: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    content: string;
}, {
    content: string;
}>;
export declare const SendMessageResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    senderId: zod.ZodNumber;
    sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, zod.ZodNull]>>;
    content: zod.ZodString;
    editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    reactions: zod.ZodArray<zod.ZodObject<{
        emoji: zod.ZodString;
        count: zod.ZodNumber;
        userIds: zod.ZodArray<zod.ZodNumber, "many">;
    }, "strip", zod.ZodTypeAny, {
        emoji: string;
        count: number;
        userIds: number[];
    }, {
        emoji: string;
        count: number;
        userIds: number[];
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}>;
/**
 * @summary Edit a message
 */
export declare const EditMessageParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
    messageId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
    messageId: number;
}, {
    conversationId: number;
    messageId: number;
}>;
export declare const EditMessageBody: zod.ZodObject<{
    content: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    content: string;
}, {
    content: string;
}>;
export declare const EditMessageResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    senderId: zod.ZodNumber;
    sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, zod.ZodNull]>>;
    content: zod.ZodString;
    editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    reactions: zod.ZodArray<zod.ZodObject<{
        emoji: zod.ZodString;
        count: zod.ZodNumber;
        userIds: zod.ZodArray<zod.ZodNumber, "many">;
    }, "strip", zod.ZodTypeAny, {
        emoji: string;
        count: number;
        userIds: number[];
    }, {
        emoji: string;
        count: number;
        userIds: number[];
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}>;
/**
 * @summary Delete a message
 */
export declare const DeleteMessageParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
    messageId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
    messageId: number;
}, {
    conversationId: number;
    messageId: number;
}>;
export declare const DeleteMessageResponse: zod.ZodObject<{
    ok: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    ok: boolean;
}, {
    ok: boolean;
}>;
/**
 * @summary Add an emoji reaction to a message
 */
export declare const AddReactionParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
    messageId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
    messageId: number;
}, {
    conversationId: number;
    messageId: number;
}>;
export declare const AddReactionBody: zod.ZodObject<{
    emoji: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    emoji: string;
}, {
    emoji: string;
}>;
export declare const AddReactionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    senderId: zod.ZodNumber;
    sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, zod.ZodNull]>>;
    content: zod.ZodString;
    editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    reactions: zod.ZodArray<zod.ZodObject<{
        emoji: zod.ZodString;
        count: zod.ZodNumber;
        userIds: zod.ZodArray<zod.ZodNumber, "many">;
    }, "strip", zod.ZodTypeAny, {
        emoji: string;
        count: number;
        userIds: number[];
    }, {
        emoji: string;
        count: number;
        userIds: number[];
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}>;
/**
 * @summary Remove an emoji reaction from a message
 */
export declare const RemoveReactionParams: zod.ZodObject<{
    conversationId: zod.ZodNumber;
    messageId: zod.ZodNumber;
    emoji: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    conversationId: number;
    emoji: string;
    messageId: number;
}, {
    conversationId: number;
    emoji: string;
    messageId: number;
}>;
export declare const RemoveReactionResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    senderId: zod.ZodNumber;
    sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
        id: zod.ZodNumber;
        username: zod.ZodString;
        displayName: zod.ZodString;
        avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        isOnline: zod.ZodBoolean;
        lastSeen: zod.ZodDate;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }, {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    }>, zod.ZodNull]>>;
    content: zod.ZodString;
    editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    createdAt: zod.ZodDate;
    reactions: zod.ZodArray<zod.ZodObject<{
        emoji: zod.ZodString;
        count: zod.ZodNumber;
        userIds: zod.ZodArray<zod.ZodNumber, "many">;
    }, "strip", zod.ZodTypeAny, {
        emoji: string;
        count: number;
        userIds: number[];
    }, {
        emoji: string;
        count: number;
        userIds: number[];
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    senderId: number;
    content: string;
    reactions: {
        emoji: string;
        count: number;
        userIds: number[];
    }[];
    sender?: {
        username: string;
        displayName: string;
        id: number;
        isOnline: boolean;
        lastSeen: Date;
        createdAt: Date;
        avatarUrl?: string | null | undefined;
        bio?: string | null | undefined;
    } | null | undefined;
    editedAt?: Date | null | undefined;
}>;
/**
 * @summary Search messages across all conversations
 */
export declare const SearchMessagesQueryParams: zod.ZodObject<{
    q: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    q: string;
}, {
    q: string;
}>;
export declare const SearchMessagesResponseItem: zod.ZodObject<{
    message: zod.ZodObject<{
        id: zod.ZodNumber;
        conversationId: zod.ZodNumber;
        senderId: zod.ZodNumber;
        sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
            id: zod.ZodNumber;
            username: zod.ZodString;
            displayName: zod.ZodString;
            avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            isOnline: zod.ZodBoolean;
            lastSeen: zod.ZodDate;
            createdAt: zod.ZodDate;
        }, "strip", zod.ZodTypeAny, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }>, zod.ZodNull]>>;
        content: zod.ZodString;
        editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
        createdAt: zod.ZodDate;
        reactions: zod.ZodArray<zod.ZodObject<{
            emoji: zod.ZodString;
            count: zod.ZodNumber;
            userIds: zod.ZodArray<zod.ZodNumber, "many">;
        }, "strip", zod.ZodTypeAny, {
            emoji: string;
            count: number;
            userIds: number[];
        }, {
            emoji: string;
            count: number;
            userIds: number[];
        }>, "many">;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }>;
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    message: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    };
    conversationId: number;
}, {
    message: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    };
    conversationId: number;
}>;
export declare const SearchMessagesResponse: zod.ZodArray<zod.ZodObject<{
    message: zod.ZodObject<{
        id: zod.ZodNumber;
        conversationId: zod.ZodNumber;
        senderId: zod.ZodNumber;
        sender: zod.ZodOptional<zod.ZodUnion<[zod.ZodObject<{
            id: zod.ZodNumber;
            username: zod.ZodString;
            displayName: zod.ZodString;
            avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
            isOnline: zod.ZodBoolean;
            lastSeen: zod.ZodDate;
            createdAt: zod.ZodDate;
        }, "strip", zod.ZodTypeAny, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }, {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        }>, zod.ZodNull]>>;
        content: zod.ZodString;
        editedAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
        createdAt: zod.ZodDate;
        reactions: zod.ZodArray<zod.ZodObject<{
            emoji: zod.ZodString;
            count: zod.ZodNumber;
            userIds: zod.ZodArray<zod.ZodNumber, "many">;
        }, "strip", zod.ZodTypeAny, {
            emoji: string;
            count: number;
            userIds: number[];
        }, {
            emoji: string;
            count: number;
            userIds: number[];
        }>, "many">;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }, {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    }>;
    conversationId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    message: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    };
    conversationId: number;
}, {
    message: {
        id: number;
        createdAt: Date;
        conversationId: number;
        senderId: number;
        content: string;
        reactions: {
            emoji: string;
            count: number;
            userIds: number[];
        }[];
        sender?: {
            username: string;
            displayName: string;
            id: number;
            isOnline: boolean;
            lastSeen: Date;
            createdAt: Date;
            avatarUrl?: string | null | undefined;
            bio?: string | null | undefined;
        } | null | undefined;
        editedAt?: Date | null | undefined;
    };
    conversationId: number;
}>, "many">;
//# sourceMappingURL=api.d.ts.map